"""test

Revision ID: 416da4eec09f
Revises: 
Create Date: 2021-05-10 23:14:02.794921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416da4eec09f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_info_img', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_list_title', sa.String(length=100), nullable=True),
    sa.Column('post_info_title', sa.String(length=80), nullable=True),
    sa.Column('post_info_time', sa.String(length=50), nullable=True),
    sa.Column('post_info_img', sa.String(length=50), nullable=True),
    sa.Column('post_info_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_sale', sa.String(length=50), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('product_category_title', sa.String(length=100), nullable=True),
    sa.Column('product_img', sa.String(length=50), nullable=True),
    sa.Column('product_title', sa.String(length=50), nullable=True),
    sa.Column('product_price', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_list_title', sa.String(length=100), nullable=True),
    sa.Column('product_info_title', sa.String(length=80), nullable=True),
    sa.Column('product_info_img', sa.String(length=50), nullable=True),
    sa.Column('product_info_sale', sa.String(length=50), nullable=True),
    sa.Column('product_info_price', sa.String(length=50), nullable=True),
    sa.Column('product_simple_description', sa.Text(), nullable=True),
    sa.Column('product_info_category', sa.String(length=50), nullable=True),
    sa.Column('product_details_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('similar_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('similar_product_sale', sa.String(length=50), nullable=True),
    sa.Column('similar_product_photo', sa.String(length=50), nullable=True),
    sa.Column('similar_product_category', sa.String(length=50), nullable=True),
    sa.Column('similar_product_title', sa.String(length=50), nullable=True),
    sa.Column('similar_product_price', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar_products')
    op.drop_table('products_info')
    op.drop_table('products')
    op.drop_table('post_info')
    op.drop_table('gallery_img')
    # ### end Alembic commands ###
