"""Test

Revision ID: 50d364be9a8e
Revises: 
Create Date: 2021-05-27 14:57:47.305428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d364be9a8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_info')
    op.add_column('products', sa.Column('product_name', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('product_simple_description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('product_details_description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('product_old_price', sa.String(length=50), nullable=True))
    op.drop_column('products', 'product_category_title')
    op.drop_column('products', 'product_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_title', sa.VARCHAR(length=50), nullable=True))
    op.add_column('products', sa.Column('product_category_title', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('products', 'product_old_price')
    op.drop_column('products', 'product_details_description')
    op.drop_column('products', 'product_simple_description')
    op.drop_column('products', 'product_name')
    op.create_table('products_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_list_title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('product_info_title', sa.VARCHAR(length=80), nullable=True),
    sa.Column('product_info_img', sa.VARCHAR(length=50), nullable=True),
    sa.Column('product_info_sale', sa.VARCHAR(length=50), nullable=True),
    sa.Column('product_info_price', sa.VARCHAR(length=50), nullable=True),
    sa.Column('product_simple_description', sa.TEXT(), nullable=True),
    sa.Column('product_info_category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('product_details_description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
