"""silindi

Revision ID: 6e26e07f9193
Revises: e70c81262f6d
Create Date: 2021-05-30 23:10:28.384780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e26e07f9193'
down_revision = 'e70c81262f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('product_sub_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_sub_category', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
