"""test

Revision ID: d8fe976af0bc
Revises: 4d88b0588efe
Create Date: 2021-05-31 20:19:28.235484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fe976af0bc'
down_revision = '4d88b0588efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar_products')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_products_brand_id_brands'), 'brands', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_brand_id_brands'), type_='foreignkey')
        batch_op.drop_column('brand_id')

    op.create_table('similar_products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('similar_product_sale', sa.VARCHAR(length=50), nullable=True),
    sa.Column('similar_product_photo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('similar_product_category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('similar_product_title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('similar_product_price', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_similar_products')
    )
    # ### end Alembic commands ###
